### ISSUE TITLE
Dicebear only supports Python 3.10+ due to Union TypeError

### ISSUE THREAD

**Issue by KJHJason** [jvherck/dicebear#3]
## Problem

So I installed the latest version of dicebear, 0.4.15 but due to this line of code on [line 68 in errors.py](https://github.com/jvherck/dicebear/blob/0869241cdaf0bcb66103c30d81434ed88fec4529/dicebear/errors.py#L68), there will be a TypeError as I'm running Python 3.9.0, 
`TypeError: unsupported operand type(s) for |: 'type' and 'type'`.

```
def log_error(exception: Exception | str): # <-- Not supported in Python 3.9 and below
    _exc = exception
    logger = logging.getLogger()
    logger.setLevel(logging.ERROR)
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter(f"%(levelname)s: {_exc.__module__}: %(message)s"))
    handler.setLevel(logging.ERROR)
    logger.addHandler(handler)
    logger.error(_exc)
```

## Suggested fix
```
from typing import Union

def log_error(exception: Union[Exception, str]): # <-- Ensures backward compatibility for Python 3.9 and below
    _exc = exception
    logger = logging.getLogger()
    logger.setLevel(logging.ERROR)
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter(f"%(levelname)s: {_exc.__module__}: %(message)s"))
    handler.setLevel(logging.ERROR)
    logger.addHandler(handler)
    logger.error(_exc)
```

Thanks for reading!

**Comment by jvherck** [comment]
Thank you for bringing this up, I will try to fix and update this ASAP! (If my schedule allows, I hope to have it done within the next 24 hours.)

**Comment by jvherck** [comment]
@KJHJason I have fixed this issue and updated the package 👍🏻 Let me know if you still have any trouble!
